INSERT INTO problem_statements (category, title, statement) VALUES
('Adult Health Nursing', 'Post-operative pain management', 'A study to assess the effectiveness of structured pain management protocols on post-operative pain levels among adult surgical patients in a selected hospital.'),
('Adult Health Nursing', 'Medication adherence in hypertension', 'A study to assess the level of medication adherence and its associated factors among patients with hypertension attending a selected outpatient department.'),
('Adult Health Nursing', 'Fall risk among elderly inpatients', 'A study to assess the knowledge and practice of staff nurses regarding fall risk prevention among elderly patients admitted in medical-surgical wards.'),
('Community Health Nursing', 'Handwashing practices in rural households', 'A study to assess the knowledge and practice regarding hand hygiene among mothers of under-five children in a selected rural community.'),
('Community Health Nursing', 'Immunization coverage awareness', 'A study to assess the awareness and utilization of immunization services among mothers of infants in a selected urban slum area.'),
('Community Health Nursing', 'Waste segregation practices', 'A study to assess the knowledge and practice regarding biomedical waste segregation among healthcare workers in a selected primary health centre.'),
('Mental Health Nursing', 'Stress among caregivers', 'A study to assess the level of stress and coping strategies among caregivers of patients with chronic mental illness attending a selected psychiatric outpatient department.'),
('Mental Health Nursing', 'Stigma toward mental illness', 'A study to assess the attitude of the general public toward persons with mental illness in a selected community.'),
('Mental Health Nursing', 'Substance use among adolescents', 'A study to assess the knowledge and attitude of adolescents regarding the ill effects of substance abuse in a selected higher secondary school.'),
('Child Health Nursing', 'Exclusive breastfeeding practices', 'A study to assess the knowledge and practice regarding exclusive breastfeeding among postnatal mothers in a selected hospital.'),
('Child Health Nursing', 'Immunization myths and misconceptions', 'A study to assess the knowledge of mothers regarding common myths and misconceptions about childhood immunization in a selected community.'),
('Child Health Nursing', 'Home management of childhood diarrhoea', 'A study to assess the knowledge and practice of mothers regarding home management of diarrhoea among children under five years.'),
('OBG Nursing', 'Antenatal care service utilization', 'A study to assess the factors influencing utilization of antenatal care services among pregnant women in a selected rural area.'),
('OBG Nursing', 'Knowledge on danger signs of pregnancy', 'A study to assess the knowledge of primigravida mothers regarding danger signs of pregnancy attending a selected antenatal clinic.'),
('OBG Nursing', 'Postnatal exercises awareness', 'A study to assess the knowledge and practice regarding postnatal exercises among postnatal mothers in a selected hospital.'),
('Fundamentals of Nursing', 'Hand hygiene compliance among nursing students', 'A study to assess the compliance of hand hygiene practices among nursing students during their clinical postings in a selected hospital.'),
('Fundamentals of Nursing', 'Bed sore prevention practices', 'A study to assess the knowledge and practice of staff nurses regarding prevention of pressure ulcers among bedridden patients.'),
('Nursing Management', 'Nurses'' workload and burnout', 'A study to assess the relationship between perceived workload and burnout among staff nurses working in a selected tertiary care hospital.'),
('Nursing Management', 'Documentation practices among staff nurses', 'A study to assess the knowledge and practice regarding nursing documentation among staff nurses in a selected hospital.'),
('Nursing Education', 'Clinical anxiety among nursing students', 'A study to assess the level of anxiety and its associated factors among nursing students during their first clinical posting.'),
('Nursing Education', 'Use of simulation-based learning', 'A study to assess the effectiveness of simulation-based teaching on the skill performance of nursing students in basic life support.'),
('Community Health Nursing', 'Menstrual hygiene among adolescent girls', 'A study to assess the knowledge and practice regarding menstrual hygiene among adolescent girls in a selected school.');
